# MySQL database connecting strings
server:
  port: 5050
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/HR?createDatabaseIfNotExist=true&useSSL=true
    username: root
    password: root
    initialize: true
    platform: mysql
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL55Dialect

